### ISSUE TITLE
GPU memory, Modifying batch size

### ISSUE THREAD

**Issue by Andrew-X-Wang** [asarigun/TransGAN#3]
Hello,

I saw your comment in VITA-Group's implementation of TransGAN and started looking at your implementation here. 

Without modifying anything and attempting to run "python train.py" results in CUDA out of memory; I believe the GPU I'm using cannot handle the model size/training images that you've specified. I tried editing the batch size on lines 35 and 36 of train.py (--gener_batch_size, changing default from 64 to 32, etc.), but I get a RuntimeError of:

Output 0 of UnbindBackward is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such fuctions do not allow the otutput  views to be modified inplace. You should replace the inplace operation by an out-of-place one.

My two questions are: 
1. How would you suggest modifying the training parameters to deal with GPU running out of memory? and,
2. Is there a better way to edit the batch size, and what else do I need to change in order for the code to not break when the batch size is changed?

Thanks!

**Comment by asarigun** [comment]
Hi @Andrew-X-Wang , 

Thank you so much for being so interested in the repo. I think you can try out to ```--gener_batch_size``` as 16 and ```--dis_batch_size``` as 8 if your GPU memory is not enough. There is a good explanation for this [here](https://github.com/pytorch/pytorch/issues/16417#issuecomment-497952224). It may be more clear for you to handle this issue!

**Comment by Andrew-X-Wang** [comment]
Hi @asarigun,

Thank you for the response. My issue ended up being having slightly different versions in the venv requirements; setting the batch size as you said works fine.

I have another question regarding the training: it looks like the fid_score of the generated images is being calculated at the end of every epoch, but tries to pull data from the fid_stat file, specified as 'fid_stat/fid_stats_cifar10_train.npz'. However, this folder and file don't exist in the repo; is there supposed to be existing fid_stats_cifar10_train.npz? Making a placeholder file seems to still crash the training after a single epoch.

Thanks!

**Comment by asarigun** [comment]
Hi @Andrew-X-Wang,

Happy to hear that problem is fixed! Actually, before training, the comments have been given on creating ```fid_stat/fid_stats_cifar10_train.npz``` in ```README.md``` at ```Installation``` part. Since the file is a little bit large, just instructions have been mentioned.

**Comment by thusinh1969** [comment]
How was the training going ? Any benchmark ? Can it handle 512-1024 ? Can it run multi gpus ? This repo does not have enough info to start with I am afraid. But will try.

Steve

**Comment by asarigun** [comment]
Hi @thusinh1969,

As I mentioned in ```README.md``` part, the CIFAR-10 dataset was used in this implementation, which has 32x32x3  dimension images. I used a single GPU. However, you can change it to multiple GPUs to run by editing ```train.py```. By the way, what do you mean 512-1024? If you're talking about dimensions of images, you can use other datasets such as [CelebA](https://mmlab.ie.cuhk.edu.hk/projects/CelebA.html). I trained the model for 30 hours in a single GPU for the CIFAR10 dataset. You can find FID score results [here](https://github.com/asarigun/TransGAN/blob/main/results/wgangp_eps_optim_Adam_lr_gen_0_0001_lr_dis_0_0001_epoch_200.txt) while I trained the model on CIFAR10. If you want to generate higher resolution samples, it is up to you to change the datasets. I hope this would be helpful for you.

Best

**Comment by thusinh1969** [comment]
Thanks for the reply. I would like to exploit a new "StyleGANV2" kind of. I got a pretty good result from StyleGANV2 (custom image dataset, furniture), but it was slow to train.

I plan to run complete 512x512 or 1024x1024 output using your TransGAN. Any hint I should prepare for starting? Happy to train from scratch, and will share results/experience here. Will run 2-4 GPU 2080ti.

Thanks,
Steve

**Comment by asarigun** [comment]
Cool! Unfortunately, I haven't trained the large size of images you mentioned. The paper's authors generated 128 by 128 and 256 by 256 size images in the original paper. Maybe this [issue](https://github.com/VITA-Group/TransGAN/issues/13#issuecomment-860367997) may help you. I would be thrilled if you share the results. 

My advice could be to start a small-sized model such as TransGAN-S and then TransGAN-M and finally try TransGAN-XL as mentioned in the [v2.0](https://arxiv.org/pdf/2102.07074v2.pdf).

You can try it out at PyTorch Lightning. It would be great to see the results!

Best

**Comment by Andrew-X-Wang** [comment]
Hi @asarigun,

I'm curious about the process of calcualting the FID for other datasets. The .npz file used for fid_stat is unique to cifar-10, correct? Do you have any resources to point to with regards to how to recalculate those statistics for other datasets/target distributions?

Thanks!

--Andrew

**Comment by asarigun** [comment]
Hello @Andrew-X-Wang,

FID score measures the diversity and quality of generated samples, which means the lower value of the FID score means better sample diversity and sample quality. 

In this implementation, I worked with the CIFAR10 dataset, which means the .npz file is for just the CIFAR10 dataset. But you can find other .npz files for other datasets such as CelebA, Church, or Stl10 [here](https://github.com/VITA-Group/TransGAN/tree/master/fid_stat).

To calculate the FID scores, I used to source code that I shared at ```fid_score.py```. You can find the details there!
